### PR TITLE
Added and Modified Footer

### PR DESCRIPTION
**Pull request by abhisheknaiidu**
Modified Footer 

rav2

### CODE REVIEW

**Comment by rajat2502** [comment]
Please decrease the padding to around 20px and change the font-size and color to white to make it look better.

**Comment by rajat2502** [comment]
Also, align the Github emoji with the text of the footer

**Comment by abhisheknaiidu** [comment]
@rajat2502 Done :)

ra3

**Comment by rajat2502** [comment]
Cool!!!

**Pull request merged**
