### PR TITLE
added Random Background

### LINKED ISSUE #21: Display Random Background Picture
Currently, we have only 1 background picture of the project, which is very monotonous. We could fetch a new picture from some API so that every time user opens the page, they get to see a new picture.

### PR DESCRIPTION
**Pull request by ankushbhardwxj**
fixes #21 
Added functionality for Random Background Picture from the Yelp API

### CODE REVIEW

**Comment by ankingcodes** [comment]
@rajat2502 Please issue and merge. I'll add a gif demonstrating the behavior soon. There's a problem in Yelp API. They allow 200 requests for 60 minutes which is really bad for debugging purposes.

**Comment by ankushbhardwxj** [comment]
@rajat2502 This is a GIF demonstrating the behavior. Please review && merge 👍 
Revenous-GoogleChrome2019-12-250

**Comment by rajat2502** [comment]
Looks Good!!!

**Comment by ankushbhardwxj** [comment]
@rajat2502 I haven't been added points for this. Please update scoreboard

**Pull request merged**
