### PR TITLE
Geolocation feature

### LINKED ISSUE #5: Current location
When the user move one place to another place then he/she can't search anytime current location.Automatically it changes to current location.
`Add the current Location Feature`

### PR DESCRIPTION
**Pull request by ankushbhardwxj**
fixes #5 
Added feature which gets the current city of the user and renders list of items of that city.

### CODE REVIEW

**Comment by ankushbhardwxj** [comment]
@rajat2502 please review & merge 👍

**Comment by rajat2502** [comment]
Can you please host this version of the website?

**Comment by ankushbhardwxj** [comment]
I dont understand.

**Comment by rajat2502** [comment]
Can you host this version of website somewhere like netlify, gh-pages?

**Comment by ankingcodes** [comment]
Can you direct me to some documentation please ? Actually I haven't deployed anything before.

**Comment by ankushbhardwxj** [comment]
@rajat2502  Is it for checking the functionality of this feature ?
I can make it work in a code sandbox

**Comment by rajat2502** [comment]
Yeah sure you just have to go to https://www.netlify.com/ login via GitHub and choose the repo you want to host. Next netlify will host it itself. Later you can change the address if you want.

**Comment by ankushbhardwxj** [comment]
@rajat2502 please check this link https://5dfcb496738b6dd38d71054b--cocky-murdock-fcb2e4.netlify.com/
Since my location is not available in Yelp , so its showing results for atlanta. Please check console,

**Comment by rajat2502** [comment]
It is not working!!! Not detecting the current location.

**Comment by ankushbhardwxj** [comment]
Did you check the console ?

**Comment by ankushbhardwxj** [comment]
@rajat2502  It does show my location on my console.
I passed that exact location in the `searchYelp` function, but if Yelp's api doesnt have your location it will show some default list.
Capture

**Comment by rajat2502** [comment]
That's cool!!! Sorry I didn't noticed that.
Thanks for your contribution.

**Pull request merged**
