### PR TITLE
Footer Shrinked

### LINKED ISSUE #17: Modify Footer
Fix the footer to the bottom of the page when the content doesn't fit to the page width.

### PR DESCRIPTION
**Pull request by abhisheknaiidu**
Fixed #17

### CODE REVIEW

**Comment by rajat2502** [comment]
Why are you giving footer a height? It will look bad on the mobile view.

**Comment by abhisheknaiidu** [comment]
@rajat2502 the reason I did that because I just want two elements to be stacked on top of each other and to make sure that no overlapping is going on. 
Ohkk wait ill make some changes such that it will look good both in Mobile as well as in Web platform

**Comment by abhisheknaiidu** [comment]
@rajat2502 Now it looks fine in both the versions 
 
Screenshot :

ra_m

**Comment by rajat2502** [comment]
Cool.

**Pull request merged**
