### PR TITLE
improved business design

### LINKED ISSUE #14: Improve the design of the business component
Improving the CSS and adding some animations to make the UX better.

### PR DESCRIPTION
**Pull request by ankushbhardwxj**
Fixes #14 
@rajat2502 Please review and merge 👍 
Revenous-GoogleChrome2019-12-201

### CODE REVIEW

**Comment by rajat2502** [comment]
Decrease the box shadow of the business component

**Comment by ankushbhardwxj** [comment]
done 👍

**Comment by rajat2502** [comment]
Please host it as well

**Comment by ankushbhardwxj** [comment]
Please see at https://relaxed-goldwasser-5e6ab7.netlify.com/

**Comment by rajat2502** [comment]
That looks cool!!! just change the scale to 1.05 on hover.
like: transform: scale(1.05);

**Comment by ankushbhardwxj** [comment]
done 👍

**Comment by rajat2502** [comment]
Cool!!!

**Pull request merged**
